In [1]:
import statistics as sts
import seaborn as srn
import pandas as pd

In [96]:
#importando o arquivo csv que iremos tratar
dataset = pd.read_csv("tempo.csv", sep = ";")

dataset.head()

  Aparencia  Temperatura  Umidade       Vento Jogar
0       sol           85     85.0       FALSO   nao
1       sol           80     90.0  VERDADEIRO   nao
2   nublado           83     86.0       FALSO   sim
3     chuva           70      NaN       FALSO   sim
4     chuva           68     80.0       FALSO   sim

In [97]:
#verificando o shape
dataset.shape

(14, 5)

In [98]:
#verificando valores da coluna Aparência
agrupadoAp = dataset.groupby(['Aparencia']).size()
agrupadoAp

Aparencia
chuva      5
menos      1
nublado    3
sol        5
dtype: int64

In [124]:
#verificando a existência de valores NAs na coluna Aparência
dataset["Aparencia"].isnull().sum()

np.int64(0)

In [99]:
#tratando a coluna Aparência
dataset.loc[dataset["Aparencia"] == "menos", "Aparencia"] = "sol"
#verificando o resultado
agrupadoAp = dataset.groupby(['Aparencia']).size()
agrupadoAp

Aparencia
chuva      5
nublado    3
sol        6
dtype: int64

In [100]:
#verificando o range de valores presentes na coluna Temperatura
dataset["Temperatura"].describe()

count      14.000000
mean      155.571429
std       306.433759
min        64.000000
25%        69.250000
50%        73.500000
75%        80.750000
max      1220.000000
Name: Temperatura, dtype: float64

In [101]:
#verificando existência de valores NAs
dataset["Temperatura"].isnull().sum()

np.int64(0)

In [103]:
#tratando a coluna Temperatura (substituindo valores < -130 e > 130 pela mediana)
medianaTemp = sts.median(dataset["Temperatura"])
dataset.loc[(dataset["Temperatura"] < -130) | (dataset["Temperatura"] > 130), "Temperatura"] = medianaTemp
#verificando o resultado
dataset["Temperatura"].describe()

count    14.000000
mean     73.678571
std       6.556286
min      64.000000
25%      69.250000
50%      72.750000
75%      78.750000
max      85.000000
Name: Temperatura, dtype: float64

In [104]:
#verificando o range de valores na coluna Umidade
dataset["Umidade"].describe()

count     13.000000
mean      89.769231
std       34.540203
min       65.000000
25%       70.000000
50%       85.000000
75%       90.000000
max      200.000000
Name: Umidade, dtype: float64

In [105]:
#verificando existência de valores NAs
dataset["Umidade"].isnull().sum()

np.int64(1)

In [114]:
#tratando a coluna Umidade (substituindo valores < 0 e > 100 e valores NAs pela mediana)
medianaUmi = sts.median(dataset["Umidade"])
dataset.loc[(dataset["Umidade"] < 0) | (dataset["Umidade"] > 100), "Umidade"] = medianaUmi
dataset["Umidade"].fillna(medianaUmi, inplace = True)
#verificando o resultado
dataset["Umidade"].describe()

C:\Users\Ramones\AppData\Local\Temp\ipykernel_17084\2501697431.py:4: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  dataset["Umidade"].fillna(medianaUmi, inplace = True)

count    14.000000
mean     81.285714
std       9.585073
min      65.000000
25%      71.250000
50%      85.250000
75%      89.000000
max      95.000000
Name: Umidade, dtype: float64

In [122]:
#verificando valores da coluna Vento
agrupadoVento = dataset.groupby(["Vento"]).size()
agrupadoVento

Vento
FALSO         7
VERDADEIRO    6
dtype: int64

In [123]:
#verificando a existência de valores NAs na coluna Vento
dataset["Vento"].isnull().sum()

np.int64(1)

In [127]:
#tratando a coluna Vento
dataset["Vento"].fillna("FALSO", inplace = True)
#verificando o resultado
agrupadoAp = dataset.groupby(["Vento"]).size()
agrupadoAp

Vento
FALSO         8
VERDADEIRO    6
dtype: int64

In [129]:
#resultado final!
dataset

   Aparencia  Temperatura  Umidade       Vento Jogar
0        sol         85.0     85.0       FALSO   nao
1        sol         80.0     90.0  VERDADEIRO   nao
2    nublado         83.0     86.0       FALSO   sim
3      chuva         70.0     85.5       FALSO   sim
4      chuva         68.0     80.0       FALSO   sim
5      chuva         65.0     70.0  VERDADEIRO   nao
6        sol         64.0     65.0  VERDADEIRO   sim
7        sol         73.5     95.0       FALSO   nao
8        sol         69.0     70.0       FALSO   sim
9      chuva         75.0     85.5       FALSO   sim
10       sol         75.0     70.0  VERDADEIRO   sim
11   nublado         72.0     90.0  VERDADEIRO   sim
12   nublado         81.0     75.0       FALSO   sim
13     chuva         71.0     91.0  VERDADEIRO   nao